export {
  createPatient,
  createBhcPatient,
  createRhuPatient,
  deletePatient,
  getBhcPatientById,
  getBhcPatients,
  getPatientById,
  getPatientByIdForRole,
  getPatientDetailsList,
  getPatientDetailsListByRole,
  getPatientHealthRecords,
  getPatientRecords,
  getPatientReferrals,
  getPatients,
  getPatientsByRole,
  getRhuPatientById,
  getRhuPatients,
  linkReferralPatientToRhu,
  savePatient,
  saveBhcPatients,
  saveRhuPatients,
  updateBhcPatient,
  updatePatient,
  updateRhuPatient,
} from "./patientService";
