<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * The consultation identity on the server draft.
 *
 * `public_id` already identifies a DRAFT, but it is minted by the server on the
 * first successful autosave. A consultation that loses its connection before
 * that write has no server identity at all, which is exactly the case the
 * on-device vault exists for. `consultation_uuid` is generated by the client at
 * consultation start instead, so both copies share one identity from the very
 * first keystroke and reconnect can update the right draft rather than creating
 * a second one.
 *
 * Nullable: drafts created before this column keep working and are adopted
 * opportunistically when resumed. Nothing is backfilled here.
 *
 * Uniqueness is (owner_user_id, consultation_uuid), PARTIAL to active rows:
 *
 *  - Per owner, because the identity is client-supplied and only meaningful
 *    within one user's drafts. Every lookup is owner-scoped; a global index
 *    would let two users' uuids collide into an error neither could resolve.
 *  - Active only, because a consumed draft and the record it became
 *    legitimately share the value, and a discarded or expired row must never
 *    block the encoder from resuming that consultation.
 *
 * PostgreSQL and SQLite both support partial indexes, and the partial unique
 * index also serves the owner + uuid lookup used on reconnect. Any other driver
 * gets a plain lookup index and relies on the application-level check in
 * HealthRecordDraftService.
 */
return new class extends Migration
{
    private const UNIQUE_INDEX = 'health_record_drafts_owner_active_consultation_unique';

    private const LOOKUP_INDEX = 'health_record_drafts_owner_consultation_uuid_index';

    public function up(): void
    {
        Schema::table('health_record_drafts', function (Blueprint $table): void {
            $table->uuid('consultation_uuid')->nullable()->after('public_id');
        });

        if ($this->supportsPartialIndexes()) {
            DB::statement(
                'CREATE UNIQUE INDEX '.self::UNIQUE_INDEX.
                ' ON health_record_drafts (owner_user_id, consultation_uuid)'.
                " WHERE consultation_uuid IS NOT NULL AND status = 'active'"
            );

            return;
        }

        Schema::table('health_record_drafts', function (Blueprint $table): void {
            $table->index(['owner_user_id', 'consultation_uuid'], self::LOOKUP_INDEX);
        });
    }

    public function down(): void
    {
        if ($this->supportsPartialIndexes()) {
            DB::statement('DROP INDEX IF EXISTS '.self::UNIQUE_INDEX);
        } else {
            Schema::table('health_record_drafts', function (Blueprint $table): void {
                $table->dropIndex(self::LOOKUP_INDEX);
            });
        }

        Schema::table('health_record_drafts', function (Blueprint $table): void {
            $table->dropColumn('consultation_uuid');
        });
    }

    private function supportsPartialIndexes(): bool
    {
        return in_array(DB::connection()->getDriverName(), ['pgsql', 'sqlite'], true);
    }
};
