import { useEffect, useState } from "react";
import DashboardLayout from "../../components/layout/DashboardLayout";
import Input from "../../components/common/atoms/Input";
import Select from "../../components/common/atoms/Select";
import { apiRequest, unwrapList } from "../../services/apiClient";

const fresh = { name:"",barangay:"",address:"",contact_information:"",status:"active",rural_health_unit_id:"",alternative_rhu_ids:[] };
export default function Facilities() {
  const [bhcs,setBhcs]=useState([]), [rhus,setRhus]=useState([]), [type,setType]=useState("bhc"), [form,setForm]=useState(null), [error,setError]=useState(""), [busy,setBusy]=useState(false);
  async function load() { const [a,b]=await Promise.all([apiRequest("/barangay-health-centers"),apiRequest("/rural-health-units")]);setBhcs(unwrapList(a));setRhus(unwrapList(b)); }
  useEffect(()=>{load().catch(e=>setError(e.message));},[]);
  function edit(item) {setError("");setForm({...fresh,...item,alternative_rhu_ids:(item.alternative_rhus||[]).map(r=>r.id)});}
  async function save(e) {e.preventDefault();setBusy(true);setError("");try { const body={name:form.name,barangay:form.barangay,address:form.address,contact_information:form.contact_information,status:form.status,...(type === "bhc" ? {rural_health_unit_id:Number(form.rural_health_unit_id),alternative_rhu_ids:form.alternative_rhu_ids.filter(id=>id!==Number(form.rural_health_unit_id))} : {})};await apiRequest(`/${type === "bhc" ? "barangay-health-centers" : "rural-health-units"}${form.id ? `/${form.id}` : ""}`,{method:form.id ? "PATCH" : "POST",body});await load();setForm(null);} catch(e){setError(Object.values(e.errors||{}).flat().join(" ")||e.message);}finally{setBusy(false);} }
  return <DashboardLayout role="admin" title="Facilities"><div className="mx-auto max-w-5xl space-y-5"><p className="text-sm text-slate-500">Manage facilities and approved referral destinations. Nurse work access is managed separately in Staff Assignments.</p><div className="flex flex-wrap gap-2">{["bhc","rhu"].map(t=><button key={t} onClick={()=>{setType(t);setForm(null);}} className={`rounded-lg px-5 py-2 text-sm ${type===t?"bg-red-700 text-white":"bg-white text-slate-600"}`}>{t.toUpperCase()} Facilities</button>)}<button onClick={()=>setForm({...fresh})} className="ml-auto rounded-lg border border-red-200 bg-white px-4 py-2 text-sm text-red-700">+ Add {type.toUpperCase()}</button></div>{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-red-800">{error}</p>}
  {form && <form onSubmit={save} className="space-y-4 rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-bold">{form.id?"Edit":"Add"} {type.toUpperCase()}</h2><div className="grid gap-4 sm:grid-cols-2">{[["name","Name"],["barangay","Barangay"],["address","Address"],["contact_information","Contact information"]].map(([key,label])=><label key={key} className="text-sm">{label}<Input required={key==="name"} value={form[key]||""} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label className="text-sm">Status<Select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} options={[{value:"active",label:"Active"},{value:"inactive",label:"Inactive"}]}/></label></div>
  {type==="bhc"&&<><label className="block text-sm">Default receiving RHU<Select required placeholder="Select default RHU" value={form.rural_health_unit_id||""} onChange={e=>setForm({...form,rural_health_unit_id:Number(e.target.value)})} options={rhus.filter(r=>r.status==="active").map(r=>({value:r.id,label:r.name}))}/></label><fieldset className="rounded-lg border border-slate-200 p-4"><legend className="px-2 text-sm font-semibold">Approved alternative RHUs</legend>{rhus.filter(r=>r.status==="active"&&r.id!==Number(form.rural_health_unit_id)).map(r=><label key={r.id} className="mb-2 flex gap-2 text-sm"><input type="checkbox" checked={form.alternative_rhu_ids.includes(r.id)} onChange={e=>setForm({...form,alternative_rhu_ids:e.target.checked?[...form.alternative_rhu_ids,r.id]:form.alternative_rhu_ids.filter(id=>id!==r.id)})}/>{r.name}</label>)}</fieldset><p className="text-xs text-slate-500">Changes apply to future routing. Historical referral destinations and staff assignments remain unchanged.</p></>}
  <div className="flex gap-3"><button disabled={busy} className="rounded-lg bg-red-700 px-5 py-2 text-white">{busy?"Saving…":"Save Facility"}</button><button type="button" onClick={()=>setForm(null)} className="px-4 py-2 text-slate-600">Cancel</button></div></form>}
  <div className="grid gap-4 sm:grid-cols-2">{(type==="bhc"?bhcs:rhus).map(f=><article key={f.id} className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex justify-between gap-3"><h2 className="font-bold">{f.name}</h2><span className="text-xs text-slate-500">{f.status}</span></div><p className="mt-2 text-sm text-slate-500">{f.address||"No address recorded"}</p>{type==="bhc"&&<dl className="mt-4 space-y-2 text-sm"><div><dt className="text-xs text-slate-500">Default receiving RHU</dt><dd>{f.rural_health_unit?.name||"Not configured"}</dd></div><div><dt className="text-xs text-slate-500">Approved alternatives</dt><dd>{(f.alternative_rhus||[]).map(r=>r.name).join(", ")||"None"}</dd></div></dl>}<button onClick={()=>edit(f)} className="mt-4 text-sm font-semibold text-red-700">Edit Facility</button></article>)}</div></div></DashboardLayout>;
}
